name: teen_browser
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  restart_app: ^1.1.0+1
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  animated_text_kit: ^4.2.2
  flutter_lints: ^2.0.0
  get: ^4.6.5
  ezanimation: ^0.6.0
  assets_audio_player: ^3.0.4+3
  alert: ^2.0.1
  email_validator: ^2.0.1
  flutter_secure_storage: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - Logo.png
    - SecureAndHiddenIcon.png
    - ClearInterfaceIcon.png
    - UncommonFeaturesIcon.png
    - HelpIcon.png
    - SquadIcon.png
    - Ready.svg
    - assets/audios/ZoroEasterEggSound.mp3
    - assets/audios/StopBroDontPassSound.mp3


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400