// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKEIKFEvDLkRWZKzfLqmBll-gWkU_ojBE',
    appId: '1:70532189489:web:83ddac65ac7f0ae058f410',
    messagingSenderId: '70532189489',
    projectId: 'teen-browser',
    authDomain: 'teen-browser.firebaseapp.com',
    storageBucket: 'teen-browser.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NfTHg4qwRPVJOvjjciTAB8nHEvEj64g',
    appId: '1:70532189489:android:d15a40d5fe93308e58f410',
    messagingSenderId: '70532189489',
    projectId: 'teen-browser',
    storageBucket: 'teen-browser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzTs_OXeXIQEP2Jx68vXaslzZbtd05uDA',
    appId: '1:70532189489:ios:b011bf0e5f4da88358f410',
    messagingSenderId: '70532189489',
    projectId: 'teen-browser',
    storageBucket: 'teen-browser.appspot.com',
    iosClientId: '70532189489-nlh500u6g2c9ufnb5f5llrlhdfnr0k68.apps.googleusercontent.com',
    iosBundleId: 'com.example.teenBrowser',
  );
}
